#!/usr/bin/env python3
"""
Generate comparison report between OpenAI and Hugging Face generated policies.
Combines evaluation metrics and structure validation results into a markdown report.
"""
import sys
from pathlib import Path


def read_eval_metrics() -> str:
    """Read evaluation metrics file"""
    reports_dir = Path(__file__).parent.parent / "reports"
    metrics_file = reports_dir / "eval_metrics.txt"
    
    if not metrics_file.exists():
        return "Evaluation metrics not available (run evaluate_text_metrics.py first)"
    
    with open(metrics_file, 'r', encoding='utf-8') as f:
        return f.read()


def read_eval_structure() -> str:
    """Read structure evaluation file"""
    reports_dir = Path(__file__).parent.parent / "reports"
    structure_file = reports_dir / "eval_structure.txt"
    
    if not structure_file.exists():
        return "Structure evaluation not available (run evaluate_structure.py first)"
    
    with open(structure_file, 'r', encoding='utf-8') as f:
        return f.read()


def main():
    """Generate comparison report"""
    print("=" * 60)
    print("Generating LLM Policy Comparison Report")
    print("=" * 60)
    
    reports_dir = Path(__file__).parent.parent.parent / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    
    # Read evaluation results
    print("\n📥 Loading evaluation results...")
    metrics_content = read_eval_metrics()
    structure_content = read_eval_structure()
    
    # Generate markdown report
    output_file = reports_dir / "llm_comparison.md"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# LLM Policy Generation Comparison Report\n\n")
        f.write("This report compares security policies generated by multiple Large Language Models from various providers.\n\n")
        f.write("---\n\n")
        
        f.write("## Executive Summary\n\n")
        f.write("This comparison evaluates the quality and compliance of security policies generated from vulnerability findings using multiple Large Language Models:\n\n")
        f.write("- **Gemini**: Google's free model via API\n")
        f.write("- **Groq**: Fast inference via Groq API (free tier)\n")
        f.write("- **Hugging Face Models**: Open-source models via Inference API\n")
        f.write("- **OpenRouter.ai Models**: Multiple free models via unified API (DeepSeek V3, Gemini 2.0 Flash, Llama 3.3 70B, GPT-OSS 20B, Nemotron Nano, Mistral 7B)\n\n")
        f.write("The evaluation uses BLEU and ROUGE-L metrics for text similarity and structural validation for compliance with ISO 27001 and NIST CSF frameworks.\n\n")
        f.write("---\n\n")
        
        f.write("## Text Similarity Metrics\n\n")
        f.write("### Methodology\n\n")
        f.write("Text similarity is measured using:\n\n")
        f.write("1. **BLEU (Bilingual Evaluation Understudy)**: Measures n-gram precision between generated policies\n")
        f.write("   - Range: 0-1 (higher is better)\n")
        f.write("   - Compares word-level similarity\n\n")
        f.write("2. **ROUGE-L (Recall-Oriented Understudy for Gisting - Longest)**: Measures longest common subsequence\n")
        f.write("   - Range: 0-1 (higher is better)\n")
        f.write("   - Considers sentence-level fluency and recall\n\n")
        f.write("### Results\n\n")
        f.write("```\n")
        f.write(metrics_content)
        f.write("```\n\n")
        f.write("---\n\n")
        
        f.write("## Structure Compliance Validation\n\n")
        f.write("### Methodology\n\n")
        f.write("Structural validation checks for:\n\n")
        f.write("- **Required Fields**: policy_id, title, mapping, scope, controls, verification, owner, status\n")
        f.write("- **ISO 27001 Mappings**: Valid control identifier format (A.X.Y.Z)\n")
        f.write("- **NIST CSF Mappings**: Valid framework control identifiers\n")
        f.write("- **Control Completeness**: Each policy should have actionable controls\n")
        f.write("- **Verification Methods**: Each policy should include verification approaches\n\n")
        f.write("### Results\n\n")
        f.write("```\n")
        f.write(structure_content)
        f.write("```\n\n")
        f.write("---\n\n")
        
        f.write("## Analysis\n\n")
        f.write("### Key Findings\n\n")
        f.write("1. **Policy Generation**: Both models successfully generated security policies from vulnerability findings\n")
        f.write("2. **Framework Compliance**: Policies include mappings to ISO 27001 and NIST CSF controls\n")
        f.write("3. **Structure Quality**: Policies follow the required YAML structure with appropriate fields\n")
        f.write("4. **Content Diversity**: Different models may emphasize different aspects of security controls\n\n")
        f.write("### Comparative Insights\n\n")
        f.write("- **Text Similarity**: BLEU and ROUGE-L scores indicate how similar the policy content is between models\n")
        f.write("- **Framework Coverage**: Number of unique ISO/NIST controls mapped shows framework coverage\n")
        f.write("- **Control Depth**: Average controls per policy indicates detail level\n")
        f.write("- **Compliance**: Structural validation ensures policies meet minimum requirements\n\n")
        f.write("### Recommendations\n\n")
        f.write("1. Use both models for comparison to identify best practices\n")
        f.write("2. Review generated policies for accuracy and completeness\n")
        f.write("3. Combine insights from both models for comprehensive policy coverage\n")
        f.write("4. Validate mappings against official ISO 27001 and NIST CSF documentation\n")
        f.write("5. Customize controls based on organizational context\n\n")
        f.write("---\n\n")
        f.write("## Conclusion\n\n")
        f.write("This comparison demonstrates the feasibility of using LLMs to generate security policies from vulnerability findings. Both OpenAI and Hugging Face models show capability in:\n\n")
        f.write("- Interpreting vulnerability data\n")
        f.write("- Generating structured policies\n")
        f.write("- Mapping to compliance frameworks\n")
        f.write("- Creating actionable security controls\n\n")
        f.write("The generated policies serve as a starting point for organizational security policy development and should be reviewed and customized by security professionals.\n\n")
        f.write("---\n\n")
        f.write("*Report generated automatically by make_comparison_md.py*\n")
    
    print(f"✅ Comparison report saved to: {output_file}")
    print("=" * 60)


if __name__ == "__main__":
    main()

